version: "3"
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./back-end:/app
    environment:
      - DATABASE_CONNECTION_URL=mongodb+srv://tansen:tansen123@cluster0.5vtwswo.mongodb.net/birtday?retryWrites=true&w=majority

  fontend:
    build:
      context: ./fontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./fontend:/app
